### ISSUE TITLE
Add section to README documenting queue_classic's approach to inserting and processing jobs

### ISSUE THREAD

**Issue by joevandyk** [QueueClassic/queue_classic#138]
The goal is to make it simpler for non-queue_classic software to process queue_classic jobs.

i.e. "To process queue_classic jobs while not using the queue_classic gem, inside a transaction, call `lock_head` inside a transaction, then process/lock/etc. Watch out for ..."

"Adding jobs is a simple matter of inserting a row into the queue_classic job table."

**Comment by senny** [comment]
@joevandyk ping. Is there anything left to do here?

**Comment by joevandyk** [comment]
Looks good to me.

**Comment by senny** [comment]
@joevandyk awesome! Thank you for the blazingly fast response :yellow_heart:
