### ISSUE TITLE
After a worker crash, jobs are never unlocked

### ISSUE THREAD

**Issue by smathieu** [QueueClassic/queue_classic#165]
Since locking happens by updating the locked_at column, if the worker crashed while processing the job, the job is forever locked. 

Delayed jobs fixed it by saving the PID and Hostname of the worker in the job and then unlocking the jobs locked by the same host when a new worker starts. (https://github.com/collectiveidea/delayed_job/pull/429/files)

This is currently not possible with queue_classic as there is no locked_by column. 

I could write a cron job that unlocks job that have been locked for too long, or add a locked_until column to the jobs which would implement maximum processing time for the jobs, but both these solutions aren't ideal. 

This issue has created some real problem in our system. We've hacked around it, but I'd like to see a better solution implemented in queue_classic itself. I can do some of the code work to help fix it, but I'd be interested to know if you can think of a better solution and what fix you'd be willing to merge back in the project.

**Comment by AlexWayfer** [comment]
> I have started writing down the problem we are aiming to solve in a wiki page.
> 
> https://github.com/ryandotsmith/queue_classic/wiki/Handling-Failure

The repo has been transferred and the wiki is gone. :cry:
