### ISSUE TITLE
Allow disabling of LISTEN/NOTIFY in order to use PgBouncer transaction pooling

### ISSUE THREAD

**Issue by gregburek** [QueueClassic/queue_classic#184]
Commit 92a4516985327228f2da3381240b6dd8894be244 removed the ability of workers to use polling instead of LISTEN/NOTIFY for getting new jobs. This is an issue when pgbouncer is being used to pool database connections at the transaction level (https://wiki.postgresql.org/wiki/PgBouncer#Feature_matrix_for_pooling_modes). As it is not recommended for Postgres to accept more than a few hundred connections (https://postgres.heroku.com/blog/past/2013/11/22/connection_limit_guidance/) , this puts an upper limit on the number of workers that can be used. 

Also, in the case where time to work a job is an order of magnitude longer than the polling interval, the speed and increased responsiveness of the LISTEN/NOTIFY method of picking up jobs does not have a meaningful impact on the amount of work completed. It would be better, in this situation, to increase the concurrency of the workers above the max_connections allowed by Postgres.

**Comment by ukd1** [comment]
Closing
