### ISSUE TITLE
Enqueue not logging or triggering callback

### ISSUE THREAD

**Issue by johnklawlor** [QueueClassic/queue_classic#213]
Here's what I'm running on.

ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin10.0]
PostgreSQL 9.3.2 on x86_64-apple-darwin10.8.0, compiled by i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666) (dot 3), 64-bit
queue_classic-2.2.3 (and have also tried 3.0.0rc, which produces the same issue)
pg: 0.17.0

In one console, I run the commend
     rake qc:work DEBUG=true

In another console, I run rails c and execute the command
     QC.enqueue('p','what the!')

And this is what the first console looks like.

dhcp-10-31-165-237:mypeeps johnlawlor$ rake qc:work DEBUG=true
lib=queue-classic at=worker_initialized
lib=queue-classic at=lock_job
lib=queue-classic at=exec_sql sql="SELECT \* FROM lock_head($1, $2)"
lib=queue-classic at=establish_conn
lib=queue-classic measure=queue.lock elapsed=14
lib=queue-classic at=exec_sql sql="LISTEN \"default\""
lib=queue-classic at=exec_sql sql="UNLISTEN \"default\""
lib=queue-classic at=exec_sql sql="SELECT \* FROM lock_head($1, $2)"
lib=queue-classic measure=queue.lock elapsed=2
lib=queue-classic at=exec_sql sql="LISTEN \"default\""
lib=queue-classic at=exec_sql sql="UNLISTEN \"default\""
lib=queue-classic at=exec_sql sql="SELECT \* FROM lock_head($1, $2)"
lib=queue-classic measure=queue.lock elapsed=2
"what the!"
lib=queue-classic at=exec_sql sql="DELETE FROM queue_classic_jobs where id = $1"
lib=queue-classic measure=queue.delete elapsed=1
lib=queue-classic at=delete_job job=201
lib=queue-classic at=work job=201 elapsed=1
lib=queue-classic at=lock_job
lib=queue-classic at=exec_sql sql="SELECT \* FROM lock_head($1, $2)"
lib=queue-classic measure=queue.lock elapsed=0
lib=queue-classic at=exec_sql sql="LISTEN \"default\""
lib=queue-classic at=exec_sql sql="UNLISTEN \"default\""

As you can see the 'puts' job is executed, but there isn't a "queue.enqueue" line in the log. If I comment out all the code in the QC.enqueue function, replace it with a simple QC.log("I'm enqueueing now!"), and then execute a QC.enqueue command, I don't see "I'm enqueueing now!" in the logs (it also, obviously, does not insert the job into the queue and therefore does not execute the job).

Ultimately, the larger problem is that the enqueue function is not triggering my after_enqueue callback. Clearly the enqueue function is being called because adding debug log calls to the "process" function will appear in the console.

Also to note, the after_delete callback I have works fine. I can include my code for the callback functionality if that helps (it isn't the prettiest as this is my first foray into using and extending Ruby modules and class), but it seems like there's some issue with "enqueue" function not returning from log_yield, but I can't explain why.

I could have a complete misunderstanding of what's going on here, but please let me know if you have any ideas or experienced similar issues. Thanks!

**Comment by senny** [comment]
@johnklawlor does this still happen with the latest versions of QC?
