### ISSUE TITLE
Rails 4.2 & ActiveJob support

### ISSUE THREAD

**Issue by jipiboily** [QueueClassic/queue_classic#228]
@senny got in touch with me to talk about the support for QueueClassic in [ActiveJob](http://edgeguides.rubyonrails.org/active_job_basics.html) which will ship with Rails 4.2.

The good news is: it's mostly there! There is already an adapter in place.

There are a few things missing or that needs to be addressed in QC itself and here they are.

## Scheduling job in the future - DONE

The ActionJob interface will provide some form of `perform_later` / `enqueue_at` method. In theory, [queue_classic-later](https://github.com/QueueClassic/queue_classic-later) should work as a drop-in replacement until it's in core.

If you try to do that via ActiveJob, it will raise an error.

PR https://github.com/QueueClassic/queue_classic/pull/217 was merged.

## Connection handling - DONE

*Update*: this was done as part of https://github.com/QueueClassic/queue_classic/pull/232.

I think, if I understand well, that we should make QC use the ActiveRecord connection if it exists so it's as easy as possible to use QueueClassic with ActiveJob. This will be a breaking change though I think. My 2 cents: it's for the greater good, so we should still make that.

## Add proper doc

Probably just in the README. 
- add an Active Job specific setup bullet
- include Active Job usage doc (https://github.com/QueueClassic/queue_classic/issues/228#issuecomment-53954538)
- update Rails' doc when we add scheduling to reflect this.

## When? Who?

None of those issue will prevent Rails 4.2 to ship, obviously, and people should be able to use QC with ActiveJob, or mostly, just without all of its features. There is no rush to get that out of the door in a week. The sooner, the better IMHO though.

Personally, with a new shiny baby, I don't have much free time (what is this again?), so I am unlikely to work on that any time soon.

I think this should be part of a QC 3.1 release.

Anyone has thoughts? Want to work on one of those?

Please note that there might other smaller issues (or even big?)

/cc @senny @ryandotsmith @ukd1 @smathieu

**Comment by jipiboily** [comment]
Hey guys, sorry for the delay, I was off from the interwebs the for last 3 weeks with my family...

Anyways, glad to know @senny is using this in prod right now. The main thing to do before releasing this is getting https://github.com/QueueClassic/queue_classic/pull/217 tested. I did some manual tests, but nothing serious and it is not really possible for me to add this to our stack as we have a bunch of custom stuff that would need to be adapted and I don't have time for this now.

What we could do from here is merge it and cut a RC release this week. Would you guys be willing to try it with the job scheduling too? /cc @severin 

Would love to get that to move forward even though I have a hard time finding time to do so. :)

And yes, the build failure is a known issue, I spent a bunch of time trying to fix this and I am not willing to remove this test as it might be a connection leak too...see https://github.com/QueueClassic/queue_classic/pull/212 for more details.

**Comment by senny** [comment]
@jipiboily if scheduling is merged I can update my apps to use an RC. However I'm not using scheduling behavior.

**Comment by jipiboily** [comment]
I just released 3.1 RC1. Now only the README need to be updated with good doc for ActiveJob, and get ppl to test this in their app. I hope to use it for us in prod soon (wishing this week, let's :pray:).

**Comment by jipiboily** [comment]
@cristianbica I was looking at adding / modifying the link to it...but I am unsure which link you are talking about here...is it the one in http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters/QueueClassicAdapter.html ? Thanks!

**Comment by jipiboily** [comment]
By the way, the README should be good now, or at leat, good enough.

**Comment by cristianbica** [comment]
@jipiboily Yes I think that is the file. I don't remember exactly where were we back in September but I think we didn't had the RDoc for each adapter with some brief info. I see that there's a link to the github repo which will show the readme so it seems ok to me.

**Comment by cristianbica** [comment]
btw "This README is representing the current work for queue_classic 3.1, which is neither complete or stable" is a bit scary ... it gives me the idea of an alpha version level  ... but you have a RC so it should be complete and almost stable :)

**Comment by jipiboily** [comment]
@cristianbica awesome, let's keep it that way.

I updated the README which should now be less scary :scream:

**Comment by cristianbica** [comment]
:+1: now push to the upstream also :)

**Comment by jipiboily** [comment]
@cschramm not sure to understand what you want me to push where... :confused:

**Comment by cristianbica** [comment]
You updated the readme on your fork but not on the main repo

**Comment by jipiboily** [comment]
Oh god, how embarrassing...I thought (I was convinced!) I pushed it, and apparently not...thanks for letting me know!

**Comment by myobie** [comment]
I just deployed a rails 4.2 app using the instructions from the updated README and my ActionMailer jobs are definitely being added to the table, but the worker that runs with `rake jobs:work` seems to just get a lock over and over without every working the jobs. If I force it to work the mailers queue with `QUEUES=mailers rake jobs:work` then it does the right thing, but I would expect most rails 4.2 users to expect that queue to be one of the default ones to be watched (I did at least).

**Comment by myobie** [comment]
Just FYI, I checked 3.1.0.RC1 and it's the same (which makes sense, just wanted to be clear).

**Comment by jipiboily** [comment]
@myobie thanks for reporting this. Can you create an issue with this please? What would you expect, a note in the README stating that maybe? Didn't start to use this in a real prod app yet, working on that right now though.

**Comment by cristianbica** [comment]
How about by default QC picks jobs from any queue?

**Comment by myobie** [comment]
Created the issue here https://github.com/QueueClassic/queue_classic/issues/244

**Comment by jipiboily** [comment]
FYI, we are running this in production, finally! If all goes well, a stable release will come out soon™.

**Comment by senny** [comment]
I'm giving this one a close. Let's open new issues if we need to refine the integration.
