### ISSUE TITLE
Add a CHANGELOG?

### ISSUE THREAD

**Issue by jipiboily** [QueueClassic/queue_classic#230]
I personally love projects with CHANGELOGs. It was removed from this projet in favor of the GitHub releases...but I think they are not that good. Anyone against getting it back?

http://keepachangelog.com/

**Comment by semaperepelitsa** [comment]
Where can I find the up to date change log? Github releases are missing notes since 3.0.0.

https://github.com/QueueClassic/queue_classic/releases

**Comment by senny** [comment]
@semaperepelitsa there is none. Your best bet is to look at the commit history to get a sense of what happened.

@jipiboily we really have to get this going again.

**Comment by senny** [comment]
I restored the changelog we once had and added in the information from the GitHub releases page.

@jipiboily would be great if you could add in the missing pieces since we stopped updating GitHub releases as well.
