### ISSUE TITLE
Not All QC functions loaded after resetting DB

### ISSUE THREAD

**Issue by alkrauss48** [QueueClassic/queue_classic#239]
I have installed v3.0.0 of queue_classic and see the proper migrations in my migrations folder (so I see that `QC::Setup.create` is called), but when I reset my db through `rake db:reset`, I get the following errors when I try to start a worker with `bundle exec rake qc:work`:

```
rake aborted!
PG::UndefinedFunction: ERROR:  function lock_head(unknown, unknown) does not exist
LINE 1: SELECT * FROM lock_head($1, $2)
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Tasks: TOP => qc:work
(See full trace by running task with --trace)
```

However, this problem is fixed if I run `bundle exec rake qc:update`, which results in the following feedback:

```
NOTICE:  column created_at already exists in queue_classic_jobs.
NOTICE:  column locked_by already exists in queue_classic_jobs.
NOTICE:  function lock_head(pg_catalog.varchar) does not exist, skipping
NOTICE:  function lock_head(pg_catalog.varchar,pg_catalog.int4) does not exist, skipping
NOTICE:  function queue_classic_notify() does not exist, skipping
```

And afterwards, if I start a worker again, everything runs flawlessly. I don't think I have any strange setup, and seeing as how this issue is solvable rather easily, it's not a big deal. But the issue is here just in case!

**Comment by jipiboily** [comment]
@alkrauss48: do you still have the issue or you fixed it? Closing for now, feel free to re-open.

**Comment by alkrauss48** [comment]
Sorry, that was rude of me not to respond. I've been on a different project for a bit, so I haven't been messing with ruby much lately. I believe I had a `schema.rb`, but when I get back to playing with it, I'll hop back on here if I have any more issues.

Thanks!

**Comment by jipiboily** [comment]
No worry! Let us know when you're back on it if you face a problem.
