### ISSUE TITLE
Allow to install pg 0.18.0

### ISSUE THREAD

**Issue by rafaelfranca** [QueueClassic/queue_classic#240]
pg 0.18.0 was released yesterday and seems to be backward compatible with 0.17. Without allowing pg 0.18 the Rails test suite can't install queue_classic > 0.3.2.

**Comment by senny** [comment]
:scream: I'll take a look. Thanks for reporting :yellow_heart:

**Comment by senny** [comment]
@jipiboily would be nice to cut a new release :hamster:

**Comment by jipiboily** [comment]
Thanks for reporting! I just pushed 3.0.3 with @senny's fix. Thanks you both guys. :heart:
