### ISSUE TITLE
rake qc:create should not fail when database/table exists

### ISSUE THREAD

**Issue by haihappen** [QueueClassic/queue_classic#258]
Unlike Rails' `rake db:create` calling `rake qc:create` fails with an error when the database/table already exists. This makes the rake task not suited for automatic deployment setups, like e.g. Docker.

**working:**
```dockerfile
CMD ["rake", "db:create", "db:migrate"]
```

**NOT working:**
```dockerfile
CMD ["rake", "qc:create", "qc:work"]
```

Any chance this could be changed?

**Comment by senny** [comment]
This rake task was designed to bootstrap a project. It's not some kind of upgrade mechanism like Active Record migrations. For the case of Active Record, this project includes a generator to create the necessary migrations (including migrations to upgrade if necessary).
