### ISSUE TITLE
rails g queue_classic:install generating same migration?

### ISSUE THREAD

**Issue by vleango** [QueueClassic/queue_classic#264]
Hi,

Just wonder about the migrations that were generated: UpdateQueueClassic300, and UpdateQueueClassic302

```
class UpdateQueueClassic300 < ActiveRecord::Migration
  def self.up
    QC::Setup.update_to_3_0_0
  end

  def self.down
    QC::Setup.downgrade_from_3_0_0
  end
end

class UpdateQueueClassic302 < ActiveRecord::Migration
  def self.up
    QC::Setup.update_to_3_0_0
  end

  def self.down
    # This migration is fixing a bug, so we don't want to do anything here.
    # I didn't want to make it irreversible either, as it could prevent
    # rolling back other, unrelated, stuff.
  end
end

```

Since both of the up methods has the same line `QC::Setup.update_to_3_0_0`, is one of the migration unnecessary?

**Comment by jipiboily** [comment]
This was to fix https://github.com/QueueClassic/queue_classic/issues/233. So if you got to 3.0.0 first, you need this, if not and you installed the latest directly, it should be fine. That said, there is no big deal in having both :)

**Comment by jipiboily** [comment]
Closing, feel free to re-open if this is not satisfying or I didn't reply properly to what you needed.

**Comment by vleango** [comment]
@jipiboily  Thanks, everything went okay
