### ISSUE TITLE
Simpler support for custom worker class

### ISSUE THREAD

**Issue by bclennox** [QueueClassic/queue_classic#266]
Currently, in order to create a custom exception handler, you need to create a subclass of `QC::Worker` and override the `#handle_failure` method. In addition, you also have to create a custom Rake task to trap INT and TERM and call out to an instance of your custom worker.

The first step makes a lot of sense, but the second step seems unnecessary. It would be simpler for users if there were an API like this:

```ruby
# lib/my_worker.rb
class MyWorker < QC::Worker
  def handle_failure(job, e)
    # ...
  end
end

QC.worker_class = MyWorker
```

This is based on the unfounded assumption that it's much more common to change how exceptions are handled than how signals are handled, so it would be valuable to make the first case simpler.

I'm happy to contribute a PR if this is a feature that you guys want.

**Comment by senny** [comment]
@bclennox would #241 suffice for your needs?

**Comment by bclennox** [comment]
That is *literally* exactly what I want! I just didn't see it while searching issues.

Thanks!

**Comment by senny** [comment]
:blush: thanks for the quick response.

**Comment by bclennox** [comment]
@senny Do you know when this will make it into an official release? I didn't see it on the list for 3.2 in #250, and it's not on the 3-1-stable branch yet.

**Comment by senny** [comment]
@bclennox it will be part of `3.2`
