### ISSUE TITLE
Recommended worker implementation

### ISSUE THREAD

**Issue by bsutherland** [QueueClassic/queue_classic#283]
This is a question rather than an issue, but I wasn't sure where else to ask. Sorry about that.

We have two batch servers. If I understand the locking correctly, it should be safe to run multiple workers against the same queue on each of these batch servers right?

I'm planning to just run a number of `bundle exec rake qc:work` processes on these batch servers. Is that a reasonable approach? I'm assuming that the locking mechanism will guarantee that each task is executed and deleted by a single worker only.

Thanks.

**Comment by senny** [comment]
That's right. You can run multiple workers on the same queue. The locking will make sure that every job is only worked by one worker.
