### ISSUE TITLE
Missing queue_class:install generator 

### ISSUE THREAD

**Issue by skatkov** [QueueClassic/queue_classic#296]
## steps

1. Add 'queue_classic' gem
2. Bundle install
3. run `rails g queue_classic:install`

## result
Could not find generator 'queue_classic:install'. Maybe you meant 'sorcery:install', 'test_unit:system' or 'css:assets' 

running `rails g --help` doesn't list anything related to queue_classic as well.

## expect result
migration created

## environment

ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Rails 5.2.0

**Comment by skatkov** [comment]
I've played around with this issue and found that If i downgrade pg gem from 1.0 version to 0.18 -- generators will appear.

Here is an example application that reproduces this error.
[rails_5_2_queue_classic.zip](https://github.com/QueueClassic/queue_classic/files/1963969/rails_5_2_queue_classic.zip)

**Comment by skatkov** [comment]
This pull request #291 resolve my issue. Would be great if it could be merged.

**Comment by bwlang** [comment]
using
```
gem 'queue_classic', github: 'QueueClassic/queue_classic', branch: 'master'
```
worked for me too - maybe time for a gem release?

**Comment by ramfjord** [comment]
+1 for the Gem release! I'm wary of always pulling from master for this gem given that the current master build is reported as failing

**Comment by skatkov** [comment]
I've been asking around on twitter from people who originally maintained this gem and it seems that it's completely abandoned.

**Comment by ukd1** [comment]
@skatkov @ramfjord @bwlang; I'm working on QC again - gearing up for a new release.
