### ISSUE TITLE
Passwords sometimes need to be URI encoded (and decoded!)

### ISSUE THREAD

**Issue by Spakman** [QueueClassic/queue_classic#299]
We use QueueClassic with its own DB connection using `QC_RAILS_DATABASE=false` and `QC_DATABASE_URL`.

Unfortunately, while this works well for our passwords in development, we receive this error in production:

`URI::InvalidURIError: bad URI(is not URI?)`

I'm not going to post the password here (and I never did figure out exactly what characters made it error), but `URI.encode`-ing the password before setting the environment variable and modifying QueueClassic to `URI.decode` the read in password solved the problem for our particular password, but I realise that URI encoded characters are valid in passwords (that's why this isn't a PR)!

**Comment by ukd1** [comment]
@Spakman - I'm closing as I can't replicate without more details. If you still have this issue, feel free to comment.
