### ISSUE TITLE
Is there anything like que-scheduler for queue_classic?

### ISSUE THREAD

**Issue by coffenbacher** [QueueClassic/queue_classic#316]
My team currently uses Que, and the lightweight cron approach of https://github.com/hlascelles/que-scheduler is one of our favorite features. 

I'm considering migrating us to queue_classic, is there anything like que-scheduler already in the queue_classic or queue_classic_plus ecosystem? 

If not, I will probably try to port it.

**Comment by ukd1** [comment]
@coffenbacher nice; no it doesn't and I've not seen anything like it. Plus doesn't support it. We use https://github.com/Rykian/clockwork for general stuff, and will / are moving to k8s ``CronJob``. We'd probably consider using it if you did!
