### ISSUE TITLE
Possibility of a release version?

### ISSUE THREAD

**Issue by os6sense** [QueueClassic/queue_classic#336]
I hate to be the one asking but are we likely to see a 4.0.0 on Rubygems soon?

**Comment by ukd1** [comment]
@os6sense we were talking about this today. It'll be done shortly. We (@rainforestapp) have been running it in prod for a while now.

**Comment by os6sense** [comment]
Any chance of this this week? We're about to cut a release and it would have been nice to use a none beta version ...
