### ISSUE TITLE
Support for OracleSQL

### ISSUE THREAD

**Issue by abhitiwari1322** [QueueClassic/queue_classic#343]
I am migrating my database from Postgres to Oracle. Does this gem support OracleSql. Any specific version that support Orracle database or any other gem with same functionality for Oracle database.

**Comment by ukd1** [comment]
@abhitiwari1322 I've never tried; it really depends on the behavior of the core SQL (e.g. finding a job to lock). Assuming that worked, you'd need to change the adaptor or use a postgres fdw?

**Comment by ukd1** [comment]
Closing, as no reply.
