### ISSUE TITLE
Why #lock is not using `QC.table_name`

### ISSUE THREAD

**Issue by gmhawash** [QueueClassic/queue_classic#346]
This has bit me a few times as we're switching schemas.  All the methods in the queue.rb file are relying on `QC.table_name` except for the `#lock` method.  The `#lock` method just references `queue_classic_jobs`.  In our case, we keep all our queue entries in the public schema, and we set `QC.table_name = 'public.queue_classic_jobs'`.   In some cases, the session's search_path is still pointing to a schema other than `public` and the `#lock` method does not find any entries to process.

Why is this method not using `QC.tablename`?

**Comment by ukd1** [comment]
@gmhawash https://github.com/QueueClassic/queue_classic/blob/ac45544c1368176503b976dad42dd0aee0be5334/lib/queue_classic/queue.rb#L96 - this looks suspiciously like an oversight. There is no reason why it should not be using that method.
