### ISSUE TITLE
How to use with Capistrano

### ISSUE THREAD

**Issue by elfassy** [QueueClassic/queue_classic#70]
What's the best way to use with something like capistrano? For now i have `rake qc:work` in my deploy.rb, but just wondering if i'm missing something?

**Comment by toydestroyer** [comment]
Is there any way to do it without foreman?

**Comment by senny** [comment]
@toydestroyer sure, you might need to write some wrapper code but all you need to do is start the worker process. You can use the provided rake task or write a script on your own.
